version: "3.2"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'classeq-rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.amq-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.amq-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_cls_net
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  rabbitmq_cls_net:
    driver: bridge
