networks:
  cls_net:
    driver: bridge

x-common-config: &common-config
  volumes:
    # Replace the following paths by the paths to the directories containing
    # the data and the models
    - ./tests/data:/var/classeq/data
    - ./tests/models:/etc/classeq/models

    # Replace the following path by the path to the shared configuration file
    - ./settings/config.prod.yaml:/etc/classeq/config.yaml
  environment:
    - LOG_LEVEL=info
    - LOG_FORMAT=jsonl # Alternative valyue ansi
    - SETTINGS_PATH=/etc/classeq/config.yaml
  networks:
    - cls_net

services:
  api:
    # Inject all shared configs
    <<: *common-config

    # Service specific configs
    image: sgelias/classeq-api:latest
    container_name: classeq-api
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 800MB
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8080" ]
      interval: 10s
      timeout: 10s
      retries: 5

  watcher:
    # Inject all shared configs
    <<: *common-config

    # Service specific configs
    image: classeq-watcher:latest
    depends_on:
      - api
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: 12.0
          memory: 12GB
        reservations:
          cpus: 1.0
          memory: 1GB

  # OpenTelemetry agents
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./telemetry/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp" # UDP port for Jaeger agent
      - "16686:16686" # Web UI
      - "14268:14268" # HTTP port for spans

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./telemetry/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
