version: "3.2"

networks:
  cls_net:
    driver: bridge

x-common-config: &common-config
  volumes:
    - ./data:/var/classeq/data
  networks:
    - cls_net

services:
  api:
    # Inject all shared configs
    <<: *common-config

    # Service specific configs
    image: classeq-api:latest
    container_name: classeq-api
    ports:
      - 8080:8080
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8080" ]
      interval: 10s
      timeout: 10s
      retries: 5

  watcher:
    # Inject all shared configs
    <<: *common-config

    # Service specific configs
    image: classeq-watcher:latest
    container_name: classeq-watcher
    depends_on:
      - api
