networks:
  cls_net:
    driver: bridge

x-common-config: &common-config
  volumes:
    # Replace the following paths by the paths to the directories containing
    # the data and the models
    - ./tests/data:/var/classeq/data
    - ./tests/models:/etc/classeq/models

    # Replace the following path by the path to the shared configuration file
    - ./settings/config.prod.yaml:/etc/classeq/config.yaml
  environment:
    - LOG_LEVEL=info
    - LOG_FORMAT=jsonl # Alternative valyue ansi
    - SETTINGS_PATH=/etc/classeq/config.yaml
  networks:
    - cls_net

services:
  api:
    # Inject all shared configs
    <<: *common-config

    # Service specific configs
    image: sgelias/classeq-api:latest
    container_name: classeq-api
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 800MB
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8080" ]
      interval: 10s
      timeout: 10s
      retries: 5

  watcher:
    # Inject all shared configs
    <<: *common-config

    # Service specific configs
    image: classeq-watcher:latest
    depends_on:
      - api
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: 12.0
          memory: 12GB
        reservations:
          cpus: 1.0
          memory: 1GB
